
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 24 15:31:35 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 20;
  public static final int CHAR = 3;
  public static final int LESSE = 38;
  public static final int NAMESPACE = 16;
  public static final int GRT = 35;
  public static final int NOTEQUAL = 34;
  public static final int SEMI = 44;
  public static final int LPAREN = 10;
  public static final int CONTINUE = 26;
  public static final int LESS = 37;
  public static final int FOR = 27;
  public static final int MINUS = 29;
  public static final int STATIC = 15;
  public static final int RPAREN = 11;
  public static final int AND = 39;
  public static final int RANGE = 49;
  public static final int OR = 40;
  public static final int COMMA = 46;
  public static final int BOOL = 5;
  public static final int CLASS = 18;
  public static final int INC = 42;
  public static final int DIV = 31;
  public static final int PLUS = 28;
  public static final int ASSIGN = 41;
  public static final int IF = 21;
  public static final int DOT = 47;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int GRTE = 36;
  public static final int EQUAL = 33;
  public static final int LAMBDA = 48;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 4;
  public static final int MOD = 32;
  public static final int BREAK = 17;
  public static final int IDENT = 2;
  public static final int VOID = 24;
  public static final int LBRACK = 12;
  public static final int COLON = 45;
  public static final int LBRACE = 7;
  public static final int ELSE = 19;
  public static final int READ = 23;
  public static final int RBRACK = 13;
  public static final int RBRACE = 8;
  public static final int EXTENDS = 25;
  public static final int PROG = 6;
  public static final int DEC = 43;
  public static final int PRINT = 9;
}

